name: DEV

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  build-and-push:
    runs-on: ubuntu-22.04
    env:
      ENV: ${{ secrets.ENV }}
      REGISTRY: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Tag Docker Image
        run: |
          echo "$ENV" > .env
          docker build -t vrde-website:dev .
          docker tag vrde-website:dev "$REGISTRY"/vrde-website:dev

      - name: Push Docker Image
        run: docker push "$REGISTRY"/vrde-website:dev
